export const caseData = {
  case_id: "TVDC01-2026-REVIEW",
  asset: {
    name: "Thames Valley DC-01",
    type: "Data centre",
    region: "Thames Valley, UK",
    location_note: "Synthetic demo location near Reading. Not a real site assessment.",
  },
  review: {
    type: "Portfolio physical-risk review",
    moment: "Ahead of insurance renewal and internal asset risk update",
    primary_question:
      "What physical-risk evidence and caveats should the reviewer consider before deciding whether the current portfolio assumption can remain unchanged?",
    human_reviewer_required: true,
  },
  sources: [
    {
      id: "external_physical_risk_signal",
      name: "External Data Centre Physical Risk Signal",
      source_type: "External market / asset-class physical-risk signal",
      hazards: [
        "flooding",
        "surface_water",
        "wind_storm",
        "wildfire_smoke",
        "extreme_heat",
        "drought_water_stress",
        "power_continuity",
        "cooling_continuity",
        "business_interruption",
      ],
      granularity: "market_or_regional",
      time_horizon: "mixed_current_and_future_stress",
      useful_for: ["review_trigger", "asset_class_context", "hazard_awareness"],
      cannot_support: [
        "site_clearance",
        "pricing_decision",
        "underwriting_decision",
        "engineering_conclusion",
      ],
      caveat: "Useful as context and trigger, not as final site-level evidence.",
    },
    {
      id: "screening_level_spatial_hazard_context",
      name: "Screening-level Spatial Hazard Context",
      source_type: "Public or local screening-level hazard-context layer",
      hazards: ["flooding", "surface_water", "drainage", "wind_storm", "heat", "infrastructure_sensitivity"],
      granularity: "screening_level_native_scale",
      time_horizon: "current_or_historical_screening",
      useful_for: ["screening_level_spatial_context", "reviewer_questions", "local_context"],
      cannot_support: [
        "building_level_resilience",
        "flood_defence_status",
        "operational_readiness",
        "engineering_design",
      ],
      caveat:
        "Needs asset-location confidence, source-scale caveats, and site-level evidence before conclusions.",
    },
    {
      id: "internal_portfolio_assumption",
      name: "Standard Physical-risk Documentation Assumption",
      source_type: "Internal portfolio review assumption",
      hazards: ["general_physical_risk"],
      granularity: "portfolio_asset_record",
      time_horizon: "current_review_cycle",
      useful_for: ["business_context", "assumption_to_review"],
      cannot_support: ["independent_resilience_evidence"],
      caveat: "A record status, not independent evidence.",
    },
    {
      id: "site_resilience_notes",
      name: "Partial Site Resilience Note",
      source_type: "Asset / site resilience record",
      hazards: [
        "flooding",
        "surface_water",
        "heat",
        "power_continuity",
        "cooling_continuity",
        "water_dependency",
        "wind_storm",
        "liquid_release",
        "business_interruption",
      ],
      granularity: "site_level_incomplete",
      time_horizon: "prior_review_cycle",
      useful_for: ["existing_evidence", "gap_identification"],
      cannot_support: ["full_engineering_assessment"],
      caveat: "Missing evidence in the record does not prove absence of controls.",
    },
    {
      id: "operational_continuity_context",
      name: "Data Centre Continuity Dependency Note",
      source_type: "Operational dependency context",
      hazards: [
        "power_continuity",
        "cooling_continuity",
        "water_dependency",
        "service_disruption",
        "business_interruption",
        "contingent_business_interruption",
        "sla_exposure",
      ],
      granularity: "asset_class_operational_context",
      time_horizon: "current_operating_context",
      useful_for: ["asset_relevance", "reviewer_questions"],
      cannot_support: ["verification_of_actual_controls"],
      caveat: "Explains relevance, not site performance.",
    },
  ],
  workup: {
    must_show: [
      "source_suitability_matrix",
      "spatial_context_note",
      "temporal_context_note",
      "multi_hazard_interpretation",
      "data_centre_asset_relevance",
      "resilience_gap_table",
      "what_cannot_be_concluded",
    ],
    recommended_next_action:
      "Request current site-level resilience evidence and refer to risk engineering if evidence remains incomplete.",
    boundary:
      "No validated site-level risk, underwriting, pricing, valuation, insurability, Tier / standards compliance, BI, MFL / PML, or engineering conclusion has been made.",
  },
};

export const workupSections = [
  {
    id: "source",
    title: "Source suitability",
    short: "Checks scale, horizon, method, limits, and intended use.",
    items: [
      "Fit-for-purpose use: screening, portfolio triage, site diligence, engineering review, or insurance file note.",
      "Native scale: grid, polygon, catchment, administrative unit, postcode, or asset-level.",
      "Asset-location confidence: synthetic point, rooftop coordinate, parcel centroid, campus polygon, postcode, or inferred location.",
      "Overlay method: point-in-polygon, buffer intersection, nearest grid cell, catchment lookup, or areal weighting.",
      "Evidence type: hazard, exposure, vulnerability, adaptation, or operational resilience.",
    ],
  },
  {
    id: "hazard",
    title: "Hazard-to-evidence interpretation",
    short: "Turns hazard themes into asset-specific evidence questions.",
    items: [
      "Flooding and surface water: floor elevation, drainage, freeboard, critical equipment location, barriers, access-road floodability.",
      "Extreme heat: ASHRAE / OEM thermal limits, server inlet temperature, cooling ride-through, loss-of-cooling procedures.",
      "Drought and water stress: water source, WUE, cooling-tower demand, drought restrictions, backup water plan.",
      "Wind / storm: roof and envelope resilience, yard equipment anchorage, utility feeds, storm response, generator fuel replenishment.",
      "Power and cooling continuity: UPS, ATS, switchgear, standby generators, N+1 / 2N redundancy, single points of failure.",
    ],
  },
  {
    id: "gaps",
    title: "Resilience evidence gaps",
    short: "Records what the review file still needs before closure.",
    items: [
      "Site and asset basis: location, IT load, rack density, target availability, utility dependencies.",
      "Power continuity: utility feeds, UPS, ATS, switchgear, generators, fuel duration, testing logs.",
      "Cooling continuity: chiller / CRAH / CRAC redundancy, cooling ride-through, heat-stress limits.",
      "BCP / EOP: service interruption plan, equipment contingency, RTO / RPO, access and supplier plans.",
      "Current risk-engineering note: inspection date, open recommendations, evidence owner, and next review date.",
    ],
  },
  {
    id: "limits",
    title: "What this cannot conclude",
    short: "Keeps the demo inside safe professional boundaries.",
    items: [
      "No validated site-level conclusion.",
      "No underwriting, pricing, valuation, insurability, BI, MFL / PML, or engineering conclusion.",
      "No certification against Tier, ASHRAE, FM, TIA-942, EN 50600, or insurer standards.",
      "No claim that missing evidence means missing controls.",
    ],
  },
];
